### ISSUE TITLE
[New Data Request Form]: ETH/BTC Spot Price on Ethereum Mainnet

### ISSUE THREAD

**Issue by sajanrajdev** [tellor-io/dataSpecs#104]
### Contact Details

saj@badger.com

### Just need a new Spot Price?

ETH/BTC. Every 15 minutes max. Coinbase, Binance, Kraken, Bitfinex, Okx, Bitmart, , Bitforex

### Query Type Name

SpotPrice

### Query Type
- Spot price of ETH denominated in BTC terms with the highest frequency as possible. As per the best practices, a buffer of 15 minutes will be implemented within the consumer smart contract to allow for disputes so a price update frequency of maximum 15 minutes would be preferred.

### Purpose
- It will be used as one of the main price feeds for a synthetic BTC collateral debt position system backed solely by ETH.

### Your query parameters

`SpotPrice` query parameters:
```
1. asset
    - description: eth
    - value type: `string`
2. currency
    - description: btc
    - value type: `string`
```

### Your response type

Default SpotPrice response type:
- `abi_type: ufixed256x18 (18 decimals of precision) - packed: false `

### Dispute Considerations

- Data must be submitted as an average of multiple price sources (Exchanges APIs, CoinGecko, Coin Market Cap, etc)
- It must be formatted in its gwei representation with 18 decimals precision

### Suggested Data Sources

- Binance: https://www.binance.com/en/trade/ETH_BTC?ref=37754157&theme=dark&type=spot
- Coinbase: https://pro.coinbase.com/trade/ETH-BTC
- Kraken: https://trade.kraken.com/charts/KRAKEN:ETH-BTC
- Bitfinex: https://trading.bitfinex.com/t/ETH:BTC?demo=true
- Bitstamp: https://www.bitstamp.net/markets/eth/btc/
- Bitforex: https://www.bitforex.com/en/spot/eth_btc?inviterId=2417198
- Bitmart: https://www.bitmart.com/trade/en-US?layout=basic&symbol=ETH_BTC
- Okx: https://www.okx.com/trade-spot/eth-btc

**Comment by themandalore** [comment]
can i close this @spuddyminer , I think we're good right?

**Comment by spuddyminer** [comment]
yes, I'll close it now.
