### ISSUE TITLE
[New Data Request]: Add New SpotPrice - IRR/USD 

### ISSUE THREAD

**Issue by nonogakhi** [tellor-io/dataSpecs#111]
### Contact Details

albertiandre@tutanota.com

### Just need a new Spot Price?

IRR/USD every 1 hour or every %1 change

### Query Type Name

SpotPrice

### Description

This data price will be used to maintain IRR currency's peg to prompts on chain for use by other smart contracts.
It will accept a string uint8, its prompt, and return a uint8 its answer.

### Your query parameters

prompt

    description: the prompt the reporter will put in IRR/USD price
    value type: `uint8 memory`

### Your response type

response type: `uint8 memory`

### Suggested Data Sources

Custom cloudflare serverless function

**Comment by themandalore** [comment]
thanks for the post @nonogakhi , what is IRR?  Have a link to a price we can pull it from?  And also, for the spotPrice type, we return uin256.  We can do a custom one to uint8, but if you're open to it, you'll get more reporter support and is a faster addition for the standard.  it's also really easy conversion in solidity (. just uint8(myNumber) )

**Comment by nonogakhi** [comment]
Thanks @themandalore for your answer.
IRR is the Iranian Rials which is the national currency for Iran.
We will build multiple multiple serverless function that return the price.
The spotPrice type is not an issue. 
Thanks in advance for your guidance

**Comment by themandalore** [comment]
Awesome, well let us know when the API is up and you can pass the endpoint to reporters.  Usually it's best to just tell reporters how to fetch the data themselves(even a paid api is better than nothing), that way it's not so centralized w/regard to your input.  
But sounds good on the other stuff too.  We can also support zk-sync, but I think the networks still a little new, so I'd be cautious about going over there yet (there were 5txns yesterday from what I can tell)

**Comment by themandalore** [comment]
I'll have our reporter manually put in a price though on goerli so you can see what it might look like and test if it works for you

**Comment by spuddyminer** [comment]
Hello @nonogakhi! Here is the manual USD/IRRR [report](https://tellor.io/data-feed/): 

Also, Here is a screenshot of what this looks like on our [data-feed](https://tellor.io/data-feed/):
<img width="1097" alt="Screenshot 2023-03-08 at 10 25 08 AM" src="https://user-images.githubusercontent.com/72078372/223756237-8aa19c02-f280-4c01-a02e-57225881dbb6.png">

**Comment by spuddyminer** [comment]
@nonogakhi I've added USD/IRR to telliot. It only has one source for now, but if you want us to report it on any testnet let me know. We're on mumbai, goerli, arbitrum goerli, optimism goerli, and chiado.

**Comment by spuddyminer** [comment]
@nonogakhi I reached out via email 🤙 let us know if you need help.
