### ISSUE TITLE
[New Data Request Form]: Real-Estate/Property price feeds request 

### ISSUE THREAD

**Issue by avinash-n992** [tellor-io/dataSpecs#114]
### Contact Details

avinash.nair6@gmail.com

### Query Type Name

RentPrice/ PropertyPrice

### Description

This Query should return the price of a real estate property based on a country's zip code(s) and state's code for ex. 
California could have the 

**Input** 
Code - CA
ZipCode/ID - 90011 

**Output** 
PropertyName - (Any apartment) of San Francisco 
Property Price - 250000
PriceUnit - USD 

Other parameters of any API providing this can be handled by the oracle itself instead of the contract calling the contract calling the oracle contract for extracting this information. 

### Your query parameters

1. state
       - description : State value (e.g. CA)
       - value type: `string`
       
2. zipCode 
       - description: Zip code value of a state (e.g. 90011) (some states could have multiple zip codes, this will depend on the property location)
       - value type: `integer`

### Your response type

- state: CA
- country: San Francisco 
- location: "Hayes Valley"
- listPrice: 1059000
- owner_first_name: "MUKKAMALLA SREEDHAR & GAIND"
- owner_last_name: "KI"
- flatImage: <url>
- flatDescription: Hayes Valley is a description in the Western Addition district of San Francisco
- agentId : 393499
- agentOfficeId : 203

### Suggested Data Sources

API Vendors - 
1. Mashvisor API
2. Realty Mole Property
3. Rent Estimate

**Comment by themandalore** [comment]
Thanks for the query!  Can you give us an example API request (like the whole thing) and a valid response.  This way we can make sure that we're on track.  And you gave three example API's...do they all have every piece of info you need?

**Comment by avinash-n992** [comment]
The sample API call as requested - 
API Endpoint list - https://rapidapi.com/mashvisor-team/api/mashvisor
 
API call to find property - 
URL : https://mashvisor-api.p.rapidapi.com/property?state=CA&id=2430136
**Params:** 
state- "CA", 
id - 2430136

**Headers**
X-RapidAPI-Key - <can be found in the API Endpoint list >
X-RapidAPI-Host - mashvisor-api.p.rapidapi.com



API Output - 
[Mashvisor CA output.txt](https://github.com/tellor-io/dataSpecs/files/11143882/Mashvisor.CA.output.txt)
