### ISSUE TITLE
[New Data Request Form]: OETH/ETH Spot Price on Ethereum Mainnet

### ISSUE THREAD

**Issue by sumpg41** [tellor-io/dataSpecs#123]
### Contact Details

peter@originprotocol.com , Discord: slagathorthemammothking, TG: PGee13

### Just need a new Spot Price?

OETH / ETH, Curve, Univ3, Maverick, every 24 hours OR a price move of more than 2% from the last price 

### Query Type Name

Spot price

### Description

- Spot price of OETH denominated in ETH terms with a frequency of 24 hours OR a price move of more than 2% from the last price, if possible

### Your query parameters

```
1. asset
    - description: oeth
    - value type: `string`
2. currency
    - description: eth
    - value type: `string`
```

### Your response type

`abi_type: ufixed256x18 (18 decimals of precision) - packed: false 
`

### Dispute Considerations

- Data must be submitted as an average of multiple price sources (Exchanges APIs, CoinGecko, Coin Market Cap, etc)

- It must be formatted in its gwei representation with 18 decimals precision

### Suggested Data Sources

Curve: https://curve.fi/#/ethereum/pools/factory-v2-298/deposit

Uniswap V3: https://app.uniswap.org/#/swap?inputCurrency=0x856c4efb76c1d1ae02e20ceb03a2a6a08b0b8dc3&outputCurrency=ETH 

Maverick: https://app.mav.xyz/pool?chain=1&tokenA=0x856c4efb76c1d1ae02e20ceb03a2a6a08b0b8dc3&tokenB=0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2&fee=0.0004&width=0.001

**Comment by spuddyminer** [comment]
Thanks! We will work on finding multiple sources for the integration into the telliot client. Here is an example report on Sepolia testnet: https://sepolia.etherscan.io/tx/0x3c5b777b0ee4bef031c9fba3d709e34e66b5b4bcc430b339e2bf92634146a7f1

**Comment by 0xSpuddy** [comment]
@sumpg41 We've merged this feed into telliot-feeds main. It should be reported automatically anytime the queryId is tipped. Let us know if you need help with any integrations! https://github.com/tellor-io/telliot-feeds/pull/688
