### ISSUE TITLE
[New Data Request Form]: Price Feed Protocol

### ISSUE THREAD

**Issue by Miguelazo1921** [tellor-io/dataSpecs#140]
### Contact Details

Miguel@sugone.com

### Just need a new Spot Price?

RWA Commodity Pricing

### Query Type Name

Commodity Oracle Price Feeds

### Description

Hello Tellor,

We're in the exploratory phase of bringing local prices of goods on-chain so stake holders have a centralized location they can access these prices.

We'd love to know more how Tellor currently offers supply-chain solutions.

Look forward to discussing more in detail.

Most kindly,

Miguel A. Lizárraga

**Comment by themandalore** [comment]
Hi @Miguelazo1921 , just emailed you
