### ISSUE TITLE
[New Data Request Form]: OGV/ETH Spot Price on Ethereum Mainnet

### ISSUE THREAD

**Issue by sumpg41** [tellor-io/dataSpecs#142]
### Contact Details

peter@originprotocol.com , Discord: slagathorthemammothking, TG: PGee13

### Just need a new Spot Price?

OGV / ETH, every 24 hours OR a price move of more than 2% from the last price

### Query Type Name

Spot price

### Description

Spot price of OGV denominated in ETH terms with a frequency of 24 hours OR a price move of more than 2% from the last price, if possible

### Your query parameters

1. asset
    - description: ogv
    - value type: `string`
2. currency
    - description: eth
    - value type: `string`

### Your response type

`abi_type: ufixed256x18 (18 decimals of precision) - packed: false   
`

### Dispute Considerations

Data must be submitted as an average of multiple price sources (Exchanges APIs, CoinGecko, Coin Market Cap, etc)

It must be formatted in its gwei representation with 18 decimals precision

### Suggested Data Sources

Uniswap: https://app.uniswap.org/swap?inputCurrency=0x9c354503c38481a7a7a51629142963f98ecc12d0&outputCurrency=ETH

Bitget: https://www.bitget.com/spot/OGVUSDT?type=spot&from=referral&clacCode=0YTJ0GZ3

HTX: https://www.htx.com/en-us/trade/ogv_usdt?invite_code=d8c53

Kucoin: https://www.kucoin.com/trade/OGV-USDT?rcode=e21sNJ

MEXC: https://www.mexc.com/exchange/OGV_USDT?inviteCode=1498J

Bingx: https://bingx.com/en-us/spot/OGVUSDT/?ch=cgk_organic

Gate: https://www.gate.io/trade/OGV_USDT?ref=3018394

Bitmart: https://www.bitmart.com/trade/en-US?layout=basic&symbol=BTC_USDT

Coingecko: https://www.coingecko.com/en/coins/origin-defi-governance

**Comment by 0xSpuddy** [comment]
Closed by telliot-feeds pr #727
