### ISSUE TITLE
[New Data Request Form]: primeETH/ETH Spot Price on Ethereum Mainnet 

### ISSUE THREAD

**Issue by sumpg41** [tellor-io/dataSpecs#147]
### Contact Details

peter@originprotocol.com , Discord: slagathorthemammothking, TG: PGee13

### Just need a new Spot Price?

primeETH / ETH, every 24 hours OR a price move of more than 2% from the last price

### Query Type Name

Spot price

### Description

Spot price of primeETH denominated in ETH terms with a frequency of 24 hours OR a price move of more than 2% from the last price, if possible

### Your query parameters

1. asset
    - description: primeETH
    - value type: `string`
2. currency
    - description: eth
    - value type: `string`

### Your response type

`abi_type: ufixed256x18 (18 decimals of precision) - packed: false   
`

### Dispute Considerations

Data must be submitted as an average of multiple price sources (Exchanges APIs, CoinGecko, Coin Market Cap, etc)

It must be formatted in its gwei representation with 18 decimals precision

### Suggested Data Sources

Uniswap: https://info.uniswap.org/#/pools/0xb6934f4cf655c93e897514dc7c2af5a143b9ca22

Coingecko: https://www.coingecko.com/en/coins/prime-staked-eth

**Comment by 0xSpuddy** [comment]
@themandalore closed 🫡
