### ISSUE TITLE
[New Query Type]: DeathInfo (testnet)

### ISSUE THREAD

**Issue by rchak007** [tellor-io/dataSpecs#152]
### Contact Details

rchak1@aol.com

### Just need a new Spot Price?

N/A

### Query Type Name

DeathInfo

### Description

hi i want to create an Oracle that provides Death information so i can code a Life insurance Smart contract.
I want to do in testnet so for now i just wanted to send some dummy Identity like SSN or passport number as alive or dead.
This is just for a test project.

### Your query parameters

{"type":"DeathInfo","arg1":"ssn"}

0x0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000094465617468496e666f000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000373736e0000000000000000000000000000000000000000000000000000000000

0x956eb5ce03237fe38f53172bfc4ddfedc5c64be18aa398a4a961d5c56f5f102b

### Your response type

- abi_type: ufixed256x18 (18 decimals of precision) - packed: false ```
I can return 0 or 1 as alive or dead.

### Dispute Considerations

for now this is only for test. So i dont need dispute. 

### Suggested Data Sources

Since this a test i would just randomly report myself with different addresses.

### Form Feedback

not sure for testnet you allow any query types to be created on our own and this process is for mainnet.

**Comment by themandalore** [comment]
Yeah you can submit for anything!  So no need to get it finalized or anything.  I think you get the issue would just be how to verify it, but submit all you want!

**Comment by rchak007** [comment]
so this will get approved for Testnet? so i can start using.

**Comment by 0xSpuddy** [comment]
Hey @rchak007 just reported on sepolia that someone with ssn 666-69-6969 is not dead: https://sepolia.etherscan.io/tx/0x9592e3ec33098073ef72ec0d92b8f90ed235f8ec8dded148d7442b67b3776586 ( I don't actually know though)

hope this helps!

![Screenshot 2024-06-06 at 10 50 19 AM](https://github.com/tellor-io/dataSpecs/assets/72078372/ffbf5707-cfe9-47e7-a5ab-553f70df7ae8)

**Comment by rchak007** [comment]
ok thx..
