### ISSUE TITLE
[New Data Request Form]: 

### ISSUE THREAD

**Issue by surbhit14** [tellor-io/dataSpecs#155]
### Contact Details

surbhitagrawal716@gmail.com

### Just need a new Spot Price?

UNI/USD

### Description

UNI/USD seems to be there but it is returning me 0 on Ethereum mainnet

**Comment by 0xSpuddy** [comment]
hello @surbhit14! I don't think UNI/USD had ever been reported on mainnet before so we did just now: 
queryId: `0xb44a64a8c4f1006949b8f471594074e97c5f30ff86acffb2d2a13c00f3aa2da0`
Decoded value: `10.7528`

Does your project need UNI/USD? How often do you need it? We love to work with devs who want to integrate tellor data.

If you prefer to do things yourself we also have bots / tools that can be used for requesting data here in the repos. For testing a single tip the easiest way is with the tellor fund-a-feed to [send a tip](https://tellor.io/fund-a-feed/) (asset: uni,  currency: usd). 

I'll leave this Request form open for now. Let me know if you have any questions!
