### ISSUE TITLE
[New Data Request Form]: 

### ISSUE THREAD

**Issue by dns7030** [tellor-io/dataSpecs#156]
### Contact Details

denissuslov at ngd.neo.org

### Just need a new Spot Price?

A number of pairs. In fact I'd like to discuss support of our EVM by Tellor

### Description

At Neo.org, we are currently working on a new EVM sidechain set to launch in July of 2024.
Docs: https://docs.banelabs.org/ 

Reasons for success:
- First time Neo supports EVM
- MEV resistance through cryptography
- Established brand, supported by seasoned crypto OG whales
- Robust TVL (40 mln USD) with our 2 tokens ranking in the Top 100 by marketcap

Would love to discuss potential integration now, as the early supporters of the new chain will be able to capture a major market share.

**Comment by themandalore** [comment]
Hey Denis, hit me up @the_fett on tg.  We can set up a group and get you guys taken care of
