### ISSUE TITLE
[New Query Type]: 

### ISSUE THREAD

**Issue by abhiraj-mengade** [tellor-io/dataSpecs#159]
### Contact Details

abhiraj.mengade@outlook.com

### Just need a new Spot Price?

No, We need a Real Life Event oracle

### Query Type Name

Event Id: , Event Desc:, Outcome:

### Description

So the idea is we need an oracle for real life event verification, data could be gathered from News sources. Example of Events would be, Did France win Gold in Swimming Olympics etc etc. The use case of this for a betting Dapp. Another Important thing is we need this on the BOB chain

### Suggested Data Sources

Mostly News Sources.

**Comment by 0xSpuddy** [comment]
@abhiraj-mengade thanks for reaching out! 

Tellor contracts are already deployed on BOB, so no worries there. And, I like this use case for tellor! We are free to create custom reports more than other oracles. I just reported your example as a string query on puff-bob testnet. (It looks like bob has a new testnet called bob sepolia but just found out about it 🙃 ): 

https://testnet-explorer.gobob.xyz/tx/0x4c0f585e03246b6c6bd2cd29af497cc49649adc48352d22f3e145400387bee1d

The decode query data and value in some screenshots here:
<img width="617" alt="Screenshot 2024-08-03 at 3 49 53 PM" src="https://github.com/user-attachments/assets/d4a2e127-64bf-4276-8f93-3afe04d45e02">
<img width="233" alt="Screenshot 2024-08-03 at 3 50 22 PM" src="https://github.com/user-attachments/assets/cde77802-8dd5-45f0-82f0-6159b416285b">

It's probably not very useful for automatic smart contract functions like this, but hope you like it! Do you have any more examples or details about the data consuming protocol that you could provide that would help us formulate the dataSpec?

**Comment by 0xSpuddy** [comment]
Also, is it important for the event description to be in the oracle data report? (seems it might be sufficient just to have the query's descriptor and the event id (int?). The value being a...string or maybe bool?

**Comment by abhiraj-mengade** [comment]
Oh cool! This is great, I will come up with examples

**Comment by 0xSpuddy** [comment]
If you want, feel free to reach out to me on discord or telegram 🫡

**Comment by abhiraj-mengade** [comment]
> If you want, feel free to reach out to me on discord or telegram 🫡
Aight! Could you share your telegram
