### ISSUE TITLE
[New Data Request Form]: superOETHb/wETH Spot Price on Base

### ISSUE THREAD

**Issue by sumpg41** [tellor-io/dataSpecs#160]
### Contact Details

peter@originprotocol.com , Discord: slagathorthemammothking, TG: PGee13

### Just need a new Spot Price?

superOETHb/wETH, every 24 hours OR a price move of more than 2% from the last price

### Query Type Name

Spot price

### Description

Spot price of superOETHb denominated in ETH terms with a frequency of 24 hours OR a price move of more than 2% from the last price, if possible

### Your query parameters

1. asset
    - description: superOETHb
    - value type: `string`
2. currency
    - description: wETH
    - value type: `string`

### Your response type

`abi_type: ufixed256x18 (18 decimals of precision) - packed: false    
`

### Dispute Considerations

Data must be submitted as an average of multiple price sources (Exchanges APIs, CoinGecko, Coin Market Cap, etc)

It must be formatted in its gwei representation with 18 decimals precision

### Suggested Data Sources

Aerodrome: https://aerodrome.finance/swap?from=0xdbfefd2e8460a6ee4955a68582f85708baea60a3&to=0x4200000000000000000000000000000000000006

Aerodrome: https://aerodrome.finance/swap?from=0xdbfefd2e8460a6ee4955a68582f85708baea60a3&to=0x7002458b1df59eccb57387bc79ffc7c29e22e6f7

Coingecko: https://www.coingecko.com/en/coins/super-oeth

**Comment by themandalore** [comment]
Hey @sumpg41 , just waiting for this PR to go through so we can deploy on base mainnet for you guys:  https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/923

**Comment by 0xSpuddy** [comment]
completed (feed is live on base)
