### ISSUE TITLE
[New Data Request Form]: Fiat to Crypto 

### ISSUE THREAD

**Issue by itmilos** [tellor-io/dataSpecs#163]
### Contact Details

milos@nicky.me

### Just need a new Spot Price?

Fiat to Crypto Spot Price pairs:

	1.	BRL/BTC - Brazilian Real to Bitcoin
	2.	BRL/ETH - Brazilian Real to Ether
	3.	BRL/USDC - Brazilian Real to USD Coin
	4.	BRL/USDT - Brazilian Real to Tether
	5.	BRL/POL - Brazilian Real to Polygon
	6.	DKK/BTC - Danish Krone to Bitcoin
	7.	DKK/ETH - Danish Krone to Ether
	8.	DKK/USDC - Danish Krone to USD Coin
	9.	DKK/USDT - Danish Krone to Tether
	10.	DKK/POL - Danish Krone to Polygon
	11.	EUR/BTC - Euro to Bitcoin
	12.	EUR/ETH - Euro to Ether
	13.	EUR/USDC - Euro to USD Coin
	14.	EUR/USDT - Euro to Tether
	15.	EUR/POL - Euro to Polygon
	16.	GBP/BTC - Pound Sterling to Bitcoin
	17.	GBP/ETH - Pound Sterling to Ether
	18.	GBP/USDC - Pound Sterling to USD Coin
	19.	GBP/USDT - Pound Sterling to Tether
	20.	GBP/POL - Pound Sterling to Polygon
	21.	SEK/BTC - Swedish Krona to Bitcoin
	22.	SEK/ETH - Swedish Krona to Ether
	23.	SEK/USDC - Swedish Krona to USD Coin
	24.	SEK/USDT - Swedish Krona to Tether
	25.	SEK/POL - Swedish Krona to Polygon
	26.	USD/BTC - US Dollar to Bitcoin
	27.	USD/ETH - US Dollar to Ether
	28.	USD/USDC - US Dollar to USD Coin
	29.	USD/USDT - US Dollar to Tether
	30.	USD/POL - US Dollar to Polygon

### Query Type Name

Spot Price

### Description

We need Spot price for multiple Crypto to Fiat pairs.

**Comment by itmilos** [comment]
@0xSpuddy For http://nicky.me/

**Comment by 0xSpuddy** [comment]
Looks cool! Do they have a decentralized product that would need a decentralized oracle?
