### ISSUE TITLE
Add new Supported Data - DAI/USD

### ISSUE THREAD

**Issue by RaynHarr** [tellor-io/dataSpecs#27]
Looking to add DAI/USD to the tellor dataSpecs, to help with governance proposals where this specific feed would be utilized.

Summary - DAI / USD

Information - Current Spot Price for DAI/USD

Decimals - 18

Supported API's / exchanges (if applicable) - Coinbase, Binance, coingecko

Dispute Considerations (if applicable) - Be sure to use multiple exchanges / sources to avoid API issues or price manipulation on one exchange

**Comment by themandalore** [comment]
hey ryan, just checking in terms of priority where to put this at.  What date do you/they need it by?

**Comment by RaynHarr** [comment]
no timeline here, just a 'nice-to-have' before the proposal goes out.

**Comment by oraclown** [comment]
Closing bc DAI/USD SpotPrice added by @akremstudy . See `catalog.md` for the query data & ID. Also [here](https://github.com/tellor-io/telliot-feed-examples/blob/main/src/telliot_feed_examples/feeds/dai_usd_feed.py) for the specific data sources used for the feed.

**Comment by RaynHarr** [comment]
**Jack Nicholson grinning meme**
