### ISSUE TITLE
Replace link to DIVA Protocol data specs

### ISSUE THREAD

**Issue by Walodja1987** [tellor-io/dataSpecs#30]
## Context

In [DIVA Protocol Specific Feeds](https://github.com/tellor-io/dataSpecs/blob/main/types/DivaProtocolPolygon.md), can we please replace the link in Information of Query to point to the `main` branch: https://github.com/divaprotocol/oracles/tree/main

Also, there is a typo in Information of Query ("i" is missing)

**Comment by themandalore** [comment]
Done!  Great catches
