### ISSUE TITLE
Bring some data in rinkeby

### ISSUE THREAD

**Issue by chalex-eth** [tellor-io/dataSpecs#59]
Dear Tellor team,

I am currently working on a project and we need to implement an oracle solution, Tellor can be a very good candidate due to it's philosophy.
I would like to test some real data on a testnet to see how it behave on-chain, I already tried the SpotPrice feature for several price feed maintained on Rinkeby. 

Now I would like to try these calls inside Rinkeby : 

- APIQuery : 
{"type":"APIQuery","url":"https://api.coingecko.com/api/v3/simple/price?ids=uniswap&vs_currencies=usd&include_market_cap=false&include_24hr_vol=false&include_24hr_change=false&include_last_updated_at=falsw","key_str":"usd"}

- GasPriceOracle :
{"type":"GasPriceOracle","chainId":1,"timestamp": 1656594311}

- Snapshot :
{"type":"Snapshot","proposalId":"0xb4886ff25f454773a779be3627863181ec7dbe1fb6b6e631678610dbe3f03a88"}

Some team member in Discord advice me to post this as an issue to see if reporter can bring this data on rinkeby.

Thank you for your help,

Look forward to work together.

**Comment by themandalore** [comment]
Super cool!  We can do those.  Any information on what you need these for, would love to help make sure you have the appropriate type/robustness of the data you're using.  But happy to just answer requests too.

**Comment by chalex-eth** [comment]
Hey, thank you for the response.
So far this is more for testing and assess how easy it is to bring data on-chain with Tellor community. 
I agree that if we are using Tellor in the future, the robustness of the data source will be a key point.

Thank you look forward to work with you

**Comment by tallywiesenberg** [comment]
extra historical gas price oracle specs: it's the median of the the means of the low and high points for the 100 hundred blocks after the requested timestamp
ex...
https://owlracle.info/eth/history?from=1656594311&to=1656594411&candles=100
and, refer to this example transaction!
https://rinkeby.etherscan.io/tx/0x199062bdfbc05da0c5a5b76efe52380099a1a5132ec4877272b32f8574985e2f

**Comment by oraclown** [comment]
@chalex-eth Here's example data for a `Snapshot` query instance. I used a different proposalId, since I couldn't find the result for the one you posted above.

- [link to proposal on snapshot.org](https://snapshot.org/#/aave.eth/proposal/0xcce9760adea906176940ae5fd05bc007cc9252b524832065800635484cb5cb57)
- [example data submitted to Rinkeby Tellor oracle](https://rinkeby.etherscan.io/tx/0x88706cfe5abe73b99a421ce527406b4338fd444635876429f110f403e86614ad)

Reproduce in Solidity like so:
```js
queryId = keccak256(abi.encode("Snapshot", abi.encode("0xcce9760adea906176940ae5fd05bc007cc9252b524832065800635484cb5cb57")))
```
```
0x4ecd69403f5dc7db44ab4f11a317dd418829ea280adbabc39728909473f9ee16
```

**Comment by chalex-eth** [comment]
Thank you guys, this is amazing,
Any change to have the API query live ? 

Thank yoy

**Comment by tallywiesenberg** [comment]
hey @chalex-eth ! 
Here is, for example, the `ApiQuery` data you requested on rinkeby. I've linked to the event log for reference!
I submitted this transaction using the new `--build-feed` flag for telliot that creates support for variable query parameters like the ones you requested above.

This transaction was created with the command:
```bash
telliot-feeds -a eth-rinkeby report --build-feed --submit-once -p YOLO
```
And the query was created using the following CLI prompt...
```bash
Enter a valid Query Type: NumericApiResponse
Enter value for Query Parameter url: https://api.coingecko.com/api/v3/simple/price?ids=uniswap&vs_currencies=usd&include_market_cap=false&include_24hr_vol=false&include_24hr_change=false&include_last_updated_at=falsw
Enter value for Query Parameter parseStr: uniswap, usd
```

We've also reformatted our "any api" product from `ApiQuery` to the query type `NumericApiResponse`, so you'll see in the event log below that that is the queryType in the queryData.
https://rinkeby.etherscan.io/tx/0x1a44fd25110b35a7183e2856bf1cf2042b5e96a5f102ae3be9dc55f64cf9f7da#eventlog

You can also confirm the accuracy of the data with this tool https://www.moesif.com/solidity-abi-hex-decoder/decode

Cheers!
