### ISSUE TITLE
Add New SpotPrice - EUR/USD

### ISSUE THREAD

**Issue by RaynHarr** [tellor-io/dataSpecs#61]
Requesting to provide an active feed on Rinkeby for potential Euro stablecoins

Summary - EUR / USD

Information - Current Spot Price for EUR/USD

Decimals - 18

Supported API's / exchanges (if applicable) - Coinbase, Binance, coingecko

Dispute Considerations (if applicable) - Be sure to use multiple exchanges / sources to avoid API issues or price manipulation on one exchange

**Comment by tallywiesenberg** [comment]
This will require a new query type `CurrencyExchangeRate` I think, as the `SpotPrice` APIs do not cover pairs of traditional currencies

for instance: https://api.pro.coinbase.com/products/usd-eur/ticker returns an empty request

**Comment by themandalore** [comment]
It should still work.  Just need new API's

**Comment by oraclown** [comment]
- You can report EUR/USD spot price using `telliot-feeds -a fakeaccname report -p YOLO -qt eur-usd-spot`
- [Example tx on mumbai](https://mumbai.polygonscan.com/tx/0xe53261c8f9c939a4d8d9f5d5b93ce737f6c5ba1ee42265cfca56a8593c1cf240), would be the same on Rinkeby
- It's using https://www.exchangerate-api.com/docs/free & https://docs.pro.coinbase.com/#products as sources.

Closing this..
