### ISSUE TITLE
Suggestion: Use GH issue templates to streamline new data types

### ISSUE THREAD

**Issue by evilrobot-01** [tellor-io/dataSpecs#87]
Just a suggestion, but issue templates may help to streamline the creation of data types somewhat, saving the requestor from having to copy and paste the sample templates by simply selecting a pre-configured issue form.

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by themandalore** [comment]
@tallywiesenberg can you knock this out?

**Comment by tallywiesenberg** [comment]
Great idea!

**Comment by themandalore** [comment]
done! Thanks for the suggestion @evilrobot-01
