### ISSUE TITLE
New data type - OHM Backing

### ISSUE THREAD

**Issue by ind-igo** [tellor-io/dataSpecs#89]
Summary - Olympus liquid backing

Information - Add the ability to query a the liquid backing of Olympus, based on a subgraph query

Return value - uint256

Supported API's / exchanges (if applicable) - Subgraph

Dispute Considerations (if applicable) - If number is significantly different from previous readings

**Comment by themandalore** [comment]
Hey @ind-igo , have a link to the subgraph (if created) or since it's an event, we could likely just return the event value at a given block if that works too.  Just let us know what it is or some more info about the query

**Comment by themandalore** [comment]
@ind-igo , just following up to see if you still need it, have any examples or things we can look at to accurately put it on-chain

**Comment by ind-igo** [comment]
@themandalore So sorry, long weekend + doing discussions in the dao about how necessary this actually is. Can close this issue for the moment and reopen in the case we find this completely necessary. Apologies for the confusion 😓
