### ISSUE TITLE
Add new SpotPrice - ALBT/USD

### ISSUE THREAD

**Issue by MeisterWalnoot** [tellor-io/dataSpecs#90]
Requesting to provide an active feed on Polygon mainnet/testnet for potential ALBT/USD pairs

Summary - ALBT / USD

Information - Current Spot Price for ALBT/USD

Decimals - 18

Supported API's / exchanges (if applicable) - kucoin, coinmarketcap,  coingecko, Coinbase, Binance,

Dispute Considerations (if applicable) - Be sure to use multiple exchanges / sources to avoid API issues or price manipulation on one exchange

**Comment by MeisterWalnoot** [comment]
yeah it is the correct one thanks! 

I have sent you a dm on discord

**Comment by MeisterWalnoot** [comment]
It works like a charm on Mumbai, can you deploy it to the main net of polygon?

**Comment by spuddyminer** [comment]
Closing this issue as this spot price feed as been added to telliot.
